### ISSUE TITLE
加入常用服事列表功能

### ISSUE THREAD

**Issue by lowkingshih** [wanlong-church/service#12]
## Link
block by #11 

## 描述
下方 Nav 加上一顆愛心 icon，可將常用的篩選器存到「常用服事表」，「總表」不提供儲存篩選器的功能，但可將當前篩選器加入「常用服事表」。

## 規格
1. 下方 Nav 加上「愛心 icon」進入「常用服事表」
2. 進入「常用服事表」後根據儲存的篩選器顯示對應的篩選資料
3. 「常用服事表」可自行更換 & 儲存當前的篩選器 -> 存在 localStorage
_私心希望可以自己調整背景顏色，太麻煩的話就下次一定_
4. 「總表」篩選器列表加上「加號 icon」將當前篩選器加到「常用服事表」

**Comment by schwannden** [comment]
deprecated by https://github.com/wanlong-church/service/pull/36
