### ISSUE TITLE
api 加上錯誤處理

### ISSUE THREAD

**Issue by lowkingshih** [wanlong-church/service#14]
## 描述
目前 sheetAPI 尚未做錯誤處理，為該 api request 加上錯誤處理，錯誤時返回 500 錯誤，然後給個 message 吧，暫時沒想到錯誤訊息格式，有想法可以討論一波。

## 規格
1. 當 API 發生無法預期的錯誤時返回 500 錯誤，並加上 message

**Comment by schwannden** [comment]
closed by https://github.com/wanlong-church/service/pull/57/files
